"""add branch to sales

Revision ID: 085c1c187550
Revises: cbebe1f73d95
Create Date: 2026-03-22 23:52:16.233856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '085c1c187550'
down_revision: Union[str, Sequence[str], None] = 'cbebe1f73d95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('inventory_product_id_key'), 'inventory', type_='unique')
    op.alter_column('users', 'branch_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'branch_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(op.f('inventory_product_id_key'), 'inventory', ['product_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
