"""add branch_id to inventory_movements

Revision ID: 18d9fc3200d4
Revises: 417d67451363
Create Date: 2026-04-04 19:00:06.839941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18d9fc3200d4'
down_revision: Union[str, Sequence[str], None] = '417d67451363'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_movements', sa.Column('branch_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'inventory_movements', 'branches', ['branch_id'], ['id'])
    op.drop_constraint(op.f('sales_branch_id_fkey'), 'sales', type_='foreignkey')
    op.drop_column('sales', 'branch_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('sales_branch_id_fkey'), 'sales', 'branches', ['branch_id'], ['id'])
    op.drop_constraint(None, 'inventory_movements', type_='foreignkey')
    op.drop_column('inventory_movements', 'branch_id')
    # ### end Alembic commands ###
