"""add branch_id to sales

Revision ID: ed3ecf1783ea
Revises: 085c1c187550
Create Date: 2026-03-22 23:54:01.377149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed3ecf1783ea'
down_revision: Union[str, Sequence[str], None] = '085c1c187550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('branch_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'sales', 'branches', ['branch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'branch_id')
    # ### end Alembic commands ###
